### ISSUE TITLE
Only using half CPU

### ISSUE THREAD

**Issue by Seegee** [bes-dev/stable_diffusion.openvino#102]
For some reason, this caps out at 50% CPU usage for me. Does anyone know what I can change so it uses my full CPU?

**Comment by brmarkus** [comment]
Can you provide more details about your environment, please?
Which HW, which OS, which version of OpenVINO are you using? Are you within a VM, a Docker container?

What do you mean with "half of the CPU"?
Do you count HyperThreading in? Or considering only physical CPU-cores?

**Comment by Seegee** [comment]
I'm running on ArchLinux. Ryzen 5900X, 128GB DDR4, NVMe SSD. Honestly have no clue what version of OpenVINO, I just followed instructions from this repo.

When I say half of my CPU used, it seems to use exactly half of the cores. 12 cores are maxed to 100%, and the other 12 cores are idling. Overall CPU usage is at 50% only.

What's also weird is that even when I run 2 instances of the model at once, it still only uses about half my CPU.
