### ISSUE TITLE
AttributeError: 'PNDMScheduler' object has no attribute 'add_noise'

### ISSUE THREAD

**Issue by harindercnvrg** [bes-dev/stable_diffusion.openvino#108]
I cloned the current repository and ran the following command:
`python demo.py --prompt "Photo of Emilia Clarke with a bright red hair" --init-image ./data/input.png --strength 0.5`

Full traceback:
`Traceback (most recent call last):
  File "demo.py", line 74, in <module>
    main(args)
  File "demo.py", line 43, in main
    eta = args.eta
  File "/cnvrg/test/stable_diffusion.openvino/stable_diffusion_engine.py", line 155, in __call__
    latents = self.scheduler.add_noise(init_latents, noise, timesteps)[0]
AttributeError: 'PNDMScheduler' object has no attribute 'add_noise'`

**Comment by brmarkus** [comment]
Can you comment in the used versions in your environment (cloned and installed "natively" in the OS, or within a container or within a Python virtual environment)?
The `requirement.txt` defines `diffusers==0.2.4`, which provides `PNDMScheduler`, which in deed has a `add_noise()` method.

You might want to check with `pip freeze > requirements.txt`, which version of `diffusers` you currently have installed.

**Comment by harindercnvrg** [comment]
yes, thank you for the help.
