### ISSUE TITLE
FP16 support

### ISSUE THREAD

**Issue by ngaloppo** [bes-dev/stable_diffusion.openvino#117]
Hello! Would it be possible to make FP16 models available for faster GPU execution? Since you have only made the FP32 OpenVINO IR available, there is no way to compress to FP16 with Model Optimizer.

**Comment by bes-dev** [comment]
@ngaloppo hello! We provide source [ONNX files for sd-1.4 ](https://huggingface.co/bes-dev/stable-diffusion-v1-4-onnx). Did you try to create FP16 OpenVINO IR using these ONNX models?

**Comment by ngaloppo** [comment]
I didn't realize you had released the ONNX files. Thank you, that should work!
