### ISSUE TITLE
Intel Iris Xe Graphics G7 not supported?

### ISSUE THREAD

**Issue by realkibou** [bes-dev/stable_diffusion.openvino#129]
Hi,

I used the --device GPU but it crashes without any info. It just stops and returns back to the command input. Did anyone managed to let the diffusion run on the GPU?

Greetings

**Comment by realkibou** [comment]
11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.70 GHz
There is only 1 GPU. The command I tried was 
python demo.py --device "GPU" --prompt "Street-art painting of Emilia Clarke in style of Banksy, photorealism"
and
python demo.py --device GPU --prompt "Street-art painting of Emilia Clarke in style of Banksy, photorealism"

**Comment by brmarkus** [comment]
That is how it is supposed to work.
I don't have a TigerLake at hand - but this is how I can run it on e.g. AlderLake's GPU I have available right now.

Are you under MS-Win or Linux?
Do you have an OpenVINO installation and could do a quick test with `hello_query_device` to check if OpenVINO is able to detect the GPU and initialize the GPU-plugin successfully?

I can remember there was something specific for TigerLake, e.g. see here: "https://hub.docker.com/r/openvino/ubuntu20_dev_no_samples"; pre-built Docker containers were made available with the postfix `_tgl`, which sounds like those containers had special drivers or patches included...
