### ISSUE TITLE
Provide Dockerfile and published Docker image

### ISSUE THREAD

**Issue by impredicative** [bes-dev/stable_diffusion.openvino#13]
It would help to have a Dockerfile and a published Docker image. This will allow convenient usage without having to install the requirements. Providing a Docker Compose file will also help, such as to configure the number of CPUs as per issue #10.

The Compose file could map the directories into which data is downloaded, and where the file is written out, so they're writable. As noted in issue #12, it would be great if the Docker image is fully self sufficient, so it can work entirely offline.

As a limited example, but probably not a perfect one, see https://github.com/AbdBarho/stable-diffusion-webui-docker , although I am not requesting a webUI if that's complicated.

**Comment by zackees** [comment]
Can we please add these commands in the Readme.md?

```
docker-compose build
docker-compose run stable diffusion -h
docker-compose run stable-diffusion --prompt "whatever..." --output /tmp/output/space.jpeg
```
