### ISSUE TITLE
Is it possible to run this using Intel Iris Xe Graphics? 

### ISSUE THREAD

**Issue by hourlyray1709** [bes-dev/stable_diffusion.openvino#152]
I have an intel iris xe graphics card and I am completely new to github. Can anyone tell me how, if at all possible, to utilize the GPU for image generation? Many thanks.

**Comment by brmarkus** [comment]
This is the beauty of using OpenVINO - it comes with all sorts of plugins for CPU and GPU.

There are different options depending on your environment, your operating system, versions.

With a "native" installation of OpenVINO the GPU dependencies could be installed as summarized here: https://docs.openvino.ai/2022.1/openvino_docs_install_guides_configurations_for_intel_gpu.html#linux (e.g. for OpenVINO in version v2022.1).

Check this documentation from @raymondlo84 : https://medium.com/openvino-toolkit/how-to-run-stable-diffusion-on-intel-gpus-with-openvino-840714f122b4

**Comment by brmarkus** [comment]
Do you have Stable-Diffusion of this repo working in your environment (without modifying the code)?

Have you simply tried different devices like CPU or GPU via the command-line parameter `--device`? It might already work out of the box ;-)

**Comment by hourlyray1709** [comment]
> Do you have Stable-Diffusion of this repo working in your environment (without modifying the code)?
> 
> Have you simply tried different devices like CPU or GPU via the command-line parameter `--device`? It might already work out of the box ;-)


The code is working normally but it is using CPU. 
I will try to put the param. Haven't tested it yet. What do I need to put after the param?

**Comment by brmarkus** [comment]
Look at "https://github.com/bes-dev/stable_diffusion.openvino#generate-image-from-text-description".

You could just add/change `--device GPU`.

**Comment by hourlyray1709** [comment]
> This is the beauty of using OpenVINO - it comes with all sorts of plugins for CPU and GPU.
> 
> There are different options depending on your environment, your operating system, versions.
> 
> With a "native" installation of OpenVINO the GPU dependencies could be installed as summarized here: https://docs.openvino.ai/2022.1/openvino_docs_install_guides_configurations_for_intel_gpu.html#linux (e.g. for OpenVINO in version v2022.1).
> 
> Check this documentation from @raymondlo84 : https://medium.com/openvino-toolkit/how-to-run-stable-diffusion-on-intel-gpus-with-openvino-840714f122b4

I am stuck on the step where it tells me to run the sh script. I tried using command prompt and shell but chmod doesn't seem to be a command.

**Comment by hourlyray1709** [comment]
> Look at "https://github.com/bes-dev/stable_diffusion.openvino#generate-image-from-text-description".
> 
> You could just add/change `--device GPU`.

It worked well, with GPU being used to 100%, but still doing 8s/it lol. Thank you very much!

**Comment by brmarkus** [comment]
Feel free to document your HW- and SW-environment (like CPU-generation, which Iris Xe GPU, which versions, amount of memory, etc.) - and your results could be added to the "wall of fame" under "https://github.com/bes-dev/stable_diffusion.openvino#performance".

Feel free to close the issue if no more questions.

**Comment by hourlyray1709** [comment]
> Feel free to document your HW- and SW-environment (like CPU-generation, which Iris Xe GPU, which versions, amount of memory, etc.) - and your results could be added to the "wall of fame" under "https://github.com/bes-dev/stable_diffusion.openvino#performance".
> 
> Feel free to close the issue if no more questions.

CPU: 12th Gen Intel(R) Core(TM) i5-1235U
GPU: Intel(R) Iris(R) Xe Graphics 
7gb memory

Btw how do I close the issue

**Comment by brmarkus** [comment]
> > Feel free to document your HW- and SW-environment (like CPU-generation, which Iris Xe GPU, which versions, amount of memory, etc.) - and your results could be added to the "wall of fame" under "https://github.com/bes-dev/stable_diffusion.openvino#performance".
> > Feel free to close the issue if no more questions.
> 
> CPU: 12th Gen Intel(R) Core(TM) i5-1235U GPU: Intel(R) Iris(R) Xe Graphics 7gb memory
> 
> Btw how do I close the issue

Like under "https://github.com/bes-dev/stable_diffusion.openvino#performance" could you add your results/througput ("Time per iter" - "Total time"), please?
(there were lots of dicussiions what could inpact the througput, like which CPU, which GPU, what type of memory DDR4/DDR5, memory-speed; but also which SW-parameters like batch-size, number of concurrent requests, etc.; so, providing as much info as possible would be helpful)

You as the creator of this issue should see a (green?) button to close the issue.

Have a look here: "https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue"
