### ISSUE TITLE
getting the following error

### ISSUE THREAD

**Issue by Zoranvedek** [bes-dev/stable_diffusion.openvino#17]
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error: Entry Not Found for url: https://huggingface.co/bes-dev/stable-diffusion-v1-4-openvino/resolve/main/vae.xml. (Request ID: meIMbxjucCK0UlHWmBiba)

**Comment by bes-dev** [comment]
@Zoranvedek Sorry for the inconvenience. Currently, we prepare new release with new cool features, so current version can be not working. We will fix it as soon as possible.

**Comment by Zoranvedek** [comment]
Absolutely not a problem, thank you for putting this together. Can't wait for new features. By any chance are height and width  settings coming?

**Comment by silentsilas** [comment]
Would it be worthwhile implementing caching the file, and using that as the fallback if the file can't be found?

**Comment by silentsilas** [comment]
@Zoranvedek saw that vae.xml was renamed in the repo's commit history, so here's the fix I found:

Line 45 and 46 in `stable_diffusion.py`, change it from:

```python
            hf_hub_download(repo_id=model, filename="vae.xml"),
            hf_hub_download(repo_id=model, filename="vae.bin")
```

To:

```python
            hf_hub_download(repo_id=model, filename="vae_decoder.xml"),
            hf_hub_download(repo_id=model, filename="vae_decoder.bin")
```

**Comment by ambiguous48** [comment]
This issue has been fixed for me after pulling the latest changes
