### ISSUE TITLE
25% utilitization  - 2/8 cores

### ISSUE THREAD

**Issue by herf** [bes-dev/stable_diffusion.openvino#25]
I have an Intel Xeon with 16 cores. It's running proxmox, 8 cores exposed to a container in a LXC (confirmed with /proc/cpuinfo).

This project/OpenVino is running on just 2/8 cores and top reports 25% utilization.

Is there any way to tell it to use all the cores available?

**Comment by panki27** [comment]
See https://github.com/bes-dev/stable_diffusion.openvino/issues/10#issuecomment-1232919688

**Comment by herf** [comment]
thank you (closing)
