### ISSUE TITLE
Hi, can u share the code how to export origina weights to onnx?

### ISSUE THREAD

**Issue by luohao123** [bes-dev/stable_diffusion.openvino#26]
Hi, can u share the code how to export origina weights to onnx?

**Comment by bes-dev** [comment]
@luohao123 currently it is not ready ti public release. We will release onnx exporter soon.

**Comment by luohao123** [comment]
I have made one: https://github.com/luohao123/gaintmodels/blob/master/export_df_onnx.py

**Comment by luohao123** [comment]
@bes-dev Hi, I found my exported onnnx inference result is wrong, can u release your version..

**Comment by luohao123** [comment]
ALSO i meet a lot of problemzs when exporting the onnx. For excample the triu op can not erxport and the model of unet is very huge. can not export.

**Comment by bes-dev** [comment]
@luohao123 currently diffusers library should support onnx export by default.
