### ISSUE TITLE
404 Client Error: Entry Not Found for url: https://hugging...vae.xml

### ISSUE THREAD

**Issue by iolpltuisciaoln** [bes-dev/stable_diffusion.openvino#29]
Hi, have some problems, any hint?

❯ python3.9 -m pip freeze
alembic==1.7.4
appdirs==1.4.4
argcomplete==1.12.2
argon2-cffi==20.1.0
asn1crypto==1.4.0
async-generator==1.10
attrs==20.3.0
Authlib==0.15.4
Babel==2.9.0
bcrypt==3.2.0
Beaker==1.11.0
beautifulsoup4==4.9.3
bidict==0.21.3
black==21.5b2
bleach==3.3.0
blinker==1.4
blis==0.7.8
blivet==3.3.2
Bottleneck==1.3.2
Brotli==1.0.9
bs4==0.0.1
cached-property==1.5.2
cachetools==4.2.1
catalogue==2.0.8
certifi==2020.12.5
cffi==1.14.5
chardet==3.0.4
click==8.1.3
coverage==5.4
cryptography==3.4.6
cymem==2.0.6
dearpygui==1.0.0
diffusers==0.2.4
distlib==0.3.1
dnspython==1.16.0
docker==4.4.2
docker-compose==1.28.2
email-validator==1.1.3
eventlet==0.31.0
filelock==3.0.12
Flask==1.1.4
Flask-BabelEx==0.9.4
Flask-Compress==1.10.1
Flask-Gravatar==0.5.0
Flask-Login==0.5.0
Flask-Mail==0.9.1
Flask-Migrate==2.7.0
Flask-Paranoid==0.2.0
Flask-Principal==0.4.0
Flask-Security-Too==4.1.2
Flask-SocketIO==5.1.1
Flask-SQLAlchemy==2.5.1
Flask-WTF==0.15.1
ftfy==6.1.1
google==3.0.0
google-api-core==1.26.0
google-api-python-client==1.12.8
google-auth==1.27.0
google-auth-httplib2==0.0.4
google-auth-oauthlib==0.4.2
googleapis-common-protos==1.53.0
greenlet==1.1.2
httpagentparser==1.9.1
httplib2==0.19.0
huggingface-hub==0.9.1
humanize==3.2.0
idna==2.10
imageio==2.9.0
img2pdf==0.4.0
importlib-metadata==4.12.0
iniparse==0.5
invoke==1.5.0
ipykernel==5.4.3
ipython==7.20.0
itsdangerous==1.1.0
jedi==0.18.0
Jinja2==3.1.2
joblib==1.0.1
jupyter-client==6.1.11
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
langcodes==3.3.0
ldap3==2.9.1
lit==0.11.1
lxml==4.6.2
Mako==1.1.4
MarkupSafe==2.1.1
mistune==0.8.4
mock==4.0.3
murmurhash==1.0.8
mypy-extensions==0.4.3
natsort==7.1.1
nbclient==0.5.2
nbconvert==6.0.7
nest-asyncio==1.5.1
netifaces==0.10.9
NeuroTools==0.3.1
notebook==6.2.0
numexpr==2.7.2
numpy==1.19.5
oauthlib==3.1.0
opencv-python==4.5.5.64
openvino==2022.1.0
ordered-set==4.0.2
packaging==20.9
pandas==1.2.2
parso==0.8.1
passlib==1.7.4
Paste==3.5.0
pathspec==0.8.1
pathy==0.6.2
pbr==5.5.1
pgadmin4==5.7
pid==3.0.4
pikepdf==2.9.2
Pillow==8.1.0
pipenv==2020.11.15
powerline-mem-segment==2.4.1
preshed==3.0.7
productmd==1.31
prometheus-client==0.9.0
prompt-toolkit==3.0.18
protobuf==3.15.3
psutil==5.8.0
psycopg2-binary==2.8.6
ptpython==3.0.17
pycairo==1.20.0
pydantic==1.9.2
pygame==2.0.1
Pygments==2.8.0
PyHamcrest==2.0.2
pykickstart==3.32
PyNaCl==1.4.0
pyparsing==3.0.9
PyQt5==5.15.2
PyQt5-sip==12.8.1
pyrsistent==0.17.3
python-dotenv==0.15.0
python-engineio==4.2.1
python-socketio==5.4.1
python-xlib==0.29
pytoml==0.1.21
pytz==2021.1
PyYAML==6.0
QScintilla==2.11.6
regex==2021.4.4
requests==2.25.1
requests-file==1.5.1
requests-oauthlib==1.3.0
rsa==4.7.2
sacremoses==0.0.53
scipy==1.9.0
scour==0.38.2
selenium==3.141.0
Send2Trash==1.5.0
setproctitle==1.2.2
simplejson==3.17.5
six==1.16.0
smart-open==5.2.1
soupsieve==2.2
spacy==3.4.1
spacy-legacy==3.0.10
spacy-loggers==1.0.3
speaklater==1.3
speaklater3==1.4
SQLAlchemy==1.3.24
sqlparse==0.4.2
srsly==2.4.4
sshtunnel==0.4.0
tables==3.6.1
Tempita==0.5.2
termcolor==1.1.0
terminado==0.9.2
texttable==1.6.3
thinc==8.1.0
tokenizers==0.12.1
toml==0.10.2
torch==1.12.1
tornado==6.1
tqdm==4.64.0
transformers==4.16.2
typer==0.4.2
typing_extensions==4.3.0
ua-parser==0.10.0
uritemplate==3.0.1
urllib3==1.26.3
user-agents==2.2.0
virtualenv==20.4.2
virtualenv-clone==0.5.4
w3lib==1.22.0
wasabi==0.10.1
wcwidth==0.2.5
websocket-client==0.57.0
Werkzeug==1.0.1
WTForms==2.3.3
wxPython==4.1.1
xlrd==2.0.1
xlwt==1.3.0
yapf==0.30.0
yaspin==2.0.0
zipp==3.8.1
zope.event==4.5.0
zope.interface==5.2.0

❯ python3.9 stable_diffusion.py --prompt "Street-art painting of Emilia Clarke in style of Banksy, photorealism"

Traceback (most recent call last):
  File "/home/zm/.local/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 131, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/bes-dev/stable-diffusion-v1-4-openvino/resolve/main/vae.xml

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zm/Downloads/SOFT/StableDiffusion/stable_diffusion.py", line 179, in <module>
    main(args)
  File "/home/zm/Downloads/SOFT/StableDiffusion/stable_diffusion.py", line 144, in main
    stable_diffusion = StableDiffusion(
  File "/home/zm/Downloads/SOFT/StableDiffusion/stable_diffusion.py", line 45, in __init__
    hf_hub_download(repo_id=model, filename="vae.xml"),
  File "/home/zm/.local/lib/python3.9/site-packages/huggingface_hub/file_download.py", line 1099, in hf_hub_download
    _raise_for_status(r)
  File "/home/zm/.local/lib/python3.9/site-packages/huggingface_hub/utils/_errors.py", line 155, in _raise_for_status
    raise e
huggingface_hub.utils._errors.EntryNotFoundError: 404 Client Error: Entry Not Found for url: https://huggingface.co/bes-dev/stable-diffusion-v1-4-openvino/resolve/main/vae.xml. (Request ID: 6a3sLwi7XxwZqLdYDcXpy)

**Comment by maxze** [comment]
You only need to pull the newest version of this repo as the file in question was renamed. This is fixed in the current version.

**Comment by iolpltuisciaoln** [comment]
thank you, it worked.
