### ISSUE TITLE
Inpainting stops at 26 iterations

### ISSUE THREAD

**Issue by kevin01881** [bes-dev/stable_diffusion.openvino#41]
Hello,

I set an **--num-inference-steps** argument, and gave it a value of 50. However, after 26 steps, the app called it quits and finalized the image. The image looks surprisingly great for having only done 26 steps, but I would have liked it if it did go to 50 instead like I instructed it to.

![afbeelding](https://user-images.githubusercontent.com/110641841/188370269-75bae3ec-ded8-458c-a3b1-b45f0681d66a.png)

Any ideas on why this could be happening?

Thanks!

**Comment by bes-dev** [comment]
@kevin01881 it is a valid behaviour. For inpainting total num of iterations is equal int(strength * num_inference_steps)
