### ISSUE TITLE
stroke_color can't be modified in web app

### ISSUE THREAD

**Issue by yossibiton** [bes-dev/stable_diffusion.openvino#66]
The web provides the option to change stroke_color, but the color always remains green
![image](https://user-images.githubusercontent.com/6518016/189838497-fa238da7-76ab-4dcb-8c08-c69e0ae16bae.png)

**Comment by bes-dev** [comment]
@yossibiton there are some problems with streamlit UI, we work on the new version of GUI. It will be released soon
